### ISSUE TITLE
command line arguments 

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/py-cifsdk#30]
The following command line arguments are not the same from the perl client. 

-c, -f are not short for --confidence and --format which makes it somewhat confusing going between those two clients. 

I did not analyse other potential differences, this issue is to capture the need to do that analysis.

**Comment by wesyoung** [comment]
fwiw, in the majority of cases, i just did the '--long' bits:

https://github.com/csirtgadgets/py-cifsdk/blob/master/cifsdk/client.py#L179

so in those cases where you want a "short hand" it should be easy enough to just add the short cut as shown:

https://github.com/csirtgadgets/py-cifsdk/blob/master/cifsdk/client.py#L167

wasn't anything other than "wasn't sure how many args there'd be, so made them all long hand to start thinking we can always add short cuts later..."
