### ISSUE TITLE
--submit is not working

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/py-cifsdk#51]
probably need to store true here:
https://github.com/csirtgadgets/py-cifsdk/blob/master/cifsdk/client.py#L210

probably need to read in "stdin" here:
https://github.com/csirtgadgets/py-cifsdk/blob/master/cifsdk/client.py#L352

and submit "stdin"...

The question is, stdin is a string not a dist or list of dicts, what's the best want to convert that string? In the perl sdk we expect json and json'ify it.

**Comment by wesyoung** [comment]
if you're catching std in, it should be valid json, blow it up to a list of dicts and then pass to submit...

now that i think of it, that's prob why we accepted strings in submit...
